In [14]:
import numpy as np
    

In [15]:
a=[1,2]
t=np.asarray(a)
print(t)

[1 2]


In [16]:
t=np.asarray(a,float)
print(t)

[1. 2.]


In [17]:
t.shape

(2,)

In [18]:
t=np.array([[1,2,3],[4,5,6]])
print(t)

[[1 2 3]
 [4 5 6]]


In [19]:
t.shape

(2, 3)

In [21]:
t=np.zeros((2,3))
print(t)

[[0. 0. 0.]
 [0. 0. 0.]]


In [24]:
t=np.ones((2,3))
print(t)

[[1. 1. 1.]
 [1. 1. 1.]]


In [27]:
t=np.eye(3,3)
print(t)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Random


In [34]:
x=np.random.random((4,5))
print(x)

[[0.96979995 0.28145543 0.83389743 0.52217138 0.70786545]
 [0.56831987 0.75674842 0.56759742 0.75505104 0.65165748]
 [0.21261947 0.69217648 0.53124062 0.94228955 0.86841317]
 [0.48690584 0.63540468 0.07958284 0.51060667 0.02248989]]


In [36]:
d=x.T  #Matrix Transpose
print(d)

[[0.96979995 0.56831987 0.21261947 0.48690584]
 [0.28145543 0.75674842 0.69217648 0.63540468]
 [0.83389743 0.56759742 0.53124062 0.07958284]
 [0.52217138 0.75505104 0.94228955 0.51060667]
 [0.70786545 0.65165748 0.86841317 0.02248989]]


In [41]:
c=d.reshape(1,20)
print(c)

[[0.96979995 0.56831987 0.21261947 0.48690584 0.28145543 0.75674842
  0.69217648 0.63540468 0.83389743 0.56759742 0.53124062 0.07958284
  0.52217138 0.75505104 0.94228955 0.51060667 0.70786545 0.65165748
  0.86841317 0.02248989]]


In [42]:
c=d.reshape(20,1)
print(c)

[[0.96979995]
 [0.56831987]
 [0.21261947]
 [0.48690584]
 [0.28145543]
 [0.75674842]
 [0.69217648]
 [0.63540468]
 [0.83389743]
 [0.56759742]
 [0.53124062]
 [0.07958284]
 [0.52217138]
 [0.75505104]
 [0.94228955]
 [0.51060667]
 [0.70786545]
 [0.65165748]
 [0.86841317]
 [0.02248989]]


# Range

In [46]:
a=np.arange(5)
print(a)

b=np.arange(5)
print(b)

c=a+b;
e=a-b;
f=a*b;
print(c,e,f)

[0 1 2 3 4]
[0 1 2 3 4]
[0 2 4 6 8] [0 0 0 0 0] [ 0  1  4  9 16]


In [47]:
print(a,a+1)

[0 1 2 3 4] [1 2 3 4 5]


# Inner & outer 

In [58]:
v=[1,2,3]
f=[-1,-2,-3]
r=np.inner(v,f)
g=np.outer(v,f)
print(g)
print(r)

[[-1 -2 -3]
 [-2 -4 -6]
 [-3 -6 -9]]
-14


In [59]:
np.dot(v,f)

-14

In [72]:
a=np.ones((2,3))
b=np.ones((1,2))
print(a)
t=a.sum()
t=a.sum(axis=0)
t=a.max()
print(t)

[[1. 1. 1.]
 [1. 1. 1.]]
1.0
